/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    'CreateTodo.modal': typeof import('./src/components/modals/create-todo.modal.vue')['default']
    CreateTodoModal: typeof import('./src/components/modals/create-todo-modal.vue')['default']
    LoginForm: typeof import('./src/components/login/login-form.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheCounter: typeof import('./src/components/application/the-counter.vue')['default']
    TheFooter: typeof import('./src/components/application/the-footer.vue')['default']
    TheHeader: typeof import('./src/components/application/the-header.vue')['default']
    TheInput: typeof import('./src/components/TheInput.vue')['default']
    TheNotifications: typeof import('./src/components/application/the-notifications.vue')['default']
    TheThemeBtn: typeof import('./src/components/application/the-theme-btn.vue')['default']
    TodoItem: typeof import('./src/components/todos/todo-item.vue')['default']
    TodoList: typeof import('./src/components/todos/todo-list.vue')['default']
    UserInfo: typeof import('./src/components/user/user-info.vue')['default']
    UserSelect: typeof import('./src/components/user/user-select.vue')['default']
  }
}
