<template>
  <header>
    header
    <a
      rel="noreferrer"
      href="https://github.com/vitalii-minchuk/todo-test"
      target="_blank"
      title="GitHub"
    >git</a>
  </header>
</template>
